# Generated by Django 5.1.1 on 2024-09-21 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cells', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='call',
            name='latitude',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='call',
            name='longitude',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
