# Generated by Django 5.1.1 on 2024-09-21 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('full_name', models.CharField(max_length=255, verbose_name='Имя')),
                ('phone', models.CharField(help_text='format 998913101010', max_length=12, verbose_name='Номер телефона')),
                ('relationship', models.CharField(choices=[('father', 'Отец'), ('mother', 'Мать'), ('brother', 'Брат'), ('sister', 'Сестра'), ('wife', 'Жена'), ('husband', 'Муж'), ('friend', 'Друг'), ('son', 'Сын'), ('doughter', 'Дочь'), ('other', 'Другое')], max_length=20, verbose_name='Кем приходится?')),
            ],
            options={
                'verbose_name': 'Близкие человек пользователя',
                'verbose_name_plural': 'Близкие люди пользователя',
                'db_table': 'contacts',
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('birthdate', models.DateField(verbose_name='Дата рождения')),
                ('address', models.CharField(max_length=255, verbose_name='Адрес')),
                ('extra', models.TextField()),
            ],
            options={
                'verbose_name': 'Пациенты',
                'verbose_name_plural': 'Пациенты',
                'db_table': 'members',
            },
        ),
    ]
