# Generated by Django 5.1.1 on 2024-09-21 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Call',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('status', models.CharField(choices=[('initiated', 'Вызов инициирован'), ('called', 'Вызван'), ('canceled', 'Отменен'), ('ambulance_requested', 'Вызвана скорая помощь'), ('finished', 'Вызов завершен')], max_length=20)),
                ('initiated_at', models.DateTimeField(auto_now_add=True)),
                ('called_at', models.DateTimeField(blank=True, null=True)),
                ('canceled_at', models.DateTimeField(blank=True, null=True)),
                ('ambulance_requested_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Вызов',
                'verbose_name_plural': 'Вызовы',
                'db_table': 'calls',
            },
        ),
    ]
