# Generated by Django 5.1.1 on 2024-09-21 07:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('calls', '0001_initial'),
        ('members', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='call',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='created_%(model_name)ss', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='call',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='members.member'),
        ),
        migrations.AddField(
            model_name='call',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='updated_%(model_name)ss', to=settings.AUTH_USER_MODEL),
        ),
    ]
