# Generated by Django 5.1.1 on 2024-09-21 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0003_call_latitude_call_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='call',
            name='call_id',
            field=models.CharField(blank=True, null=True),
        ),
    ]
