# Generated by Django 5.1.1 on 2024-09-22 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0004_call_call_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='call',
            name='latitude',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='call',
            name='longitude',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='call',
            name='status',
            field=models.CharField(choices=[('initiated', 'Вызов инициирован'), ('called', 'Вызван'), ('canceled', 'Отменен'), ('ambulance_requested', 'Вызвана скорая помощь'), ('finished', 'Вызов завершен')], default='initiated', max_length=20),
        ),
    ]
